<?php

return [
    [
        'id' => 1,
        'image' => 'Rectangle 1317 (1).png',
        'title' => 'Boost Your Brand Identity',
        'avatar' => 'Ellipse 162.png',
        'writer' => 'Sara Ali',
        'date' => 'July 1, 2024',
        // 'comments' => 3,
        'text' => 'Discover the key principles behind successful branding and identity.',
        'category' => "Branding",
    ],
    [
        'id' => 2,
        'image' => 'Rectangle 4632 (2).png',
        'title' => 'Digital Marketing Trends 2024',
        'avatar' => 'Ellipse 162.png',
        'writer' => 'Mohamed Fathy',
        'date' => 'June 15, 2024',
        // 'comments' => 7,
        'text' => 'Explore the latest tools and tactics in digital marketing today.',
        'category' => "Marketing",
    ],
    [
        'id' => 3,
        'image' => 'Rectangle 1317 (1).png',
        'title' => 'Choosing the Right Software',
        'avatar' => 'Ellipse 162.png',
        'writer' => 'Lina Youssef',
        'date' => 'May 30, 2024',
        // 'comments' => 5,
        'text' => 'Learn how to select the best software solutions for your team.',
        'category' => "Branding",
    ],
    [
        'id' => 4,
        'image' => 'Rectangle 1317 (1).png',
        'title' => 'Why Data Sharing Matters',
        'avatar' => 'Ellipse 162.png',
        'writer' => 'Omar Adel',
        'date' => 'May 10, 2024',
        // 'comments' => 2,
        'text' => 'Understand the importance of sharing data responsibly.',
        'category' => 'Software',
    ],
    [
        'id' => 5,
        'image' => 'Rectangle 1317 (1).png',
        'title' => 'Cookies and Online Tracking',
        'avatar' => 'Ellipse 162.png',
        'writer' => 'Nada Khaled',
        'date' => 'April 22, 2024',
        // 'comments' => 6,
        'text' => 'Everything you need to know about cookies and user tracking.',
        'category' => 'Sharing data with external parties',
    ],
    [
        'id' => 6,
        'image' => 'Rectangle 1317 (1).png',
        'title' => 'Cybersecurity Essentials',
        'avatar' => 'Ellipse 162.png',
        'writer' => 'Ahmed Samir',
        'date' => 'April 1, 2024',
        // 'comments' => 4,
        'text' => 'Protect your data and infrastructure with simple security tips.',
        'category' => 'Cookies',
    ],
    [
        'id' => 7,
        'image' => 'Rectangle 1317 (1).png',
        'title' => 'Understanding User Rights',
        'avatar' => 'Ellipse 162.png',
        'writer' => 'Yasmin Tarek',
        'date' => 'March 19, 2024',
        // 'comments' => 9,
        'text' => 'Your rights as a user and how to ensure they’re respected.',
        'category' => 'Security and Data Protection',
    ],
    [
        'id' => 8,
        'image' => 'Rectangle 1317 (1).png',
        'title' => 'Privacy Policy Updates',
        'avatar' => 'Ellipse 162.png',
        'writer' => 'Khaled Nabil',
        'date' => 'March 1, 2024',
        // 'comments' => 1,
        'text' => 'What recent changes in privacy policies mean for you.',
        'category' => 'Changes to the Privacy Policy',
    ],
    [
        'id' => 9,
        'image' => 'Rectangle 1317 (1).png',
        'title' => 'Future of Online Branding',
        'avatar' => 'Ellipse 162.png',
        'writer' => 'Reem Hassan',
        'date' => 'February 15, 2024',
        // 'comments' => 8,
        'text' => 'Where branding is heading in the digital age.',
        'category' => 'Changes to the Privacy Policy',
    ],
];
