<?php

return [
    [
        'id' => 1,
        'main_image' => 'image 30.webp',
        'client' => 'Website HSpace',
        "title" => "Website design for HSpace",
        "sec-title" => "Media",
        'description' => 'موقع شركة HSpace Software',
        'category' => 'انظمة برمجية',
        "sub-category" => "موقع الكتروني",
        'before_images' => ['image 2.webp', 'image 3.webp', 'image 4.webp'],
        'after_images' => ['image 5.webp', 'image 6.webp', 'image 7.webp'],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://manzzeli-eg.com/'
    ],
    [
        'id' => 1000,
        'main_image' => 'logo-ar.webp',
        'client' => 'الماجدية ريزدنس',
        "title" => "الموقع تم تصميمه من قبل فرناس",
        "sec-title" => "ميديا",
        'description' => 'عدّ شركة الماجدية من أوائل الشركات الرائدة في المجال العقاري، وتقوم بدور متكامل في السوق السعودي العقاري، ببناء الفلل السكنية والمباني التجارية ذات جودة عالية، والتخطيط والاستثمار العقاري لتساهم في نمو اقتصاد السوق العقاري من خلال مشاريع غطت فيها مناطق مختلفة من المملكة العربية السعودية تلبي فيها احتياجات العملاء وتحقيق أهداف المستثمرين',
        'category' => 'انظمة برمجية',
        "sub-category" => "موقع الكتروني",
        'before_images' => ['screencapture-almajdiah-2025-08-21-11_28_18.webp', 'screencapture-almajdiah-2025-08-21-11_28_18 - Copy (2).webp', 'screencapture-almajdiah-2025-08-21-11_28_18 - Copy (3).webp', 'screencapture-almajdiah-2025-08-21-11_28_18 - Copy.webp'],
        'after_images' => [],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
        ],
        'url' => 'https://almajdiah.com/'
    ],
    [
        'id' => 1001,
        'main_image' => 'Thabat-logo-Versions-01-1024x557.webp',
        'client' => 'ثبات',
        "title" => "الموقع تم تصميمه من قبل فرناس",
        "sec-title" => "ميديا",
        'description' => 'ثبات للتطوير العقاري امتداد لتاريخ ثبات للمقاولات، تواصل تقديم المشاريع الواعدة عبر اختيار مواقع متميزة تعكس الأصالة والحداثة، بمرافق متكاملة وبيئة نابضة بالحياة، حيث يجتمع الاستقرار مع الابتكار في كل وجهة',
        'category' => 'انظمة برمجية',
        "sub-category" => "موقع الكتروني",
        'before_images' => ['screencapture-thabatred-2025-08-21-10_58_28 - Copy (7).webp', "screencapture-thabatred-2025-08-21-10_58_28.webp", 'screencapture-thabatred-2025-08-21-10_58_28 - Copy (2).webp', 'screencapture-thabatred-2025-08-21-10_58_28 - Copy (3).webp', 'screencapture-thabatred-2025-08-21-10_58_28 - Copy (5).webp'],
        'after_images' => [],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
        ],
        'url' => 'https://thabatred.com/'
    ],
    [
        'id' => 1002,
        'main_image' => 'logo-2025-1-1536x1176.webp',
        'client' => 'ريستاتكس',
        "title" => "الموقع تم تصميمه من قبل فرناس",
        "sec-title" => "ميديا",
        'description' => 'يهدف المعرض إلى تسليط الضوء على دور القطاع العقاري في التأثير على جهود تنويع مصادر الاستثمار كأحد أهم أهداف رؤية المملكة 2030. كما ينقل التطورات في القطاع العقاري السعودي في المشاريع السكنية والتجارية متعددة الاستخدامات وتوجهاتها',
        'category' => 'انظمة برمجية',
        "sub-category" => "موقع الكتروني",
        'before_images' => ['screencapture-restatex-ar-home-2025-08-21-11_09_42 - Copy (5).webp', 'screencapture-restatex-ar-home-2025-08-21-11_09_42 - Copy (2).webp', 'screencapture-restatex-ar-home-2025-08-21-11_09_42 - Copy (3).webp', 'screencapture-restatex-ar-home-2025-08-21-11_09_42 - Copy (4).webp'],
        'after_images' => [],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
        ],
        'url' => 'https://restatex.com/ar/home-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9/'
    ],
    [
        'id' => 20,
        'main_image' => 'Logo-02.webp',
        'client' => 'Saya',
        "title" => "Saya",
        "sec-title" => "Media",
        'description' => ' كلُّ منحنى يروي قصة، وكلُّ خطٍّ يُنقش بعناية. هنا تبدأ رحلة منتجك.',
        "sub-category" => "Saya",
        'category' => 'التسويق',
        'before_images' => ['web 1-01.webp', 'web 2-01.webp', 'web 3-01.webp', 'web 4-01.webp', 'web 5-01.webp', 'website 6-01.webp'],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/'
    ],
    [
        'id' => 21,
        'main_image' => 'logo track.webp',
        'client' => 'The Track Fit',
        "title" => "The Track Fit",
        "sec-title" => "Media",
        'description' => ' وسيلة قوية لسرد القصص تُجسّد جوهر العلامة التجارية من خلال صور جذّابة وسرد مؤثر. فإنتاج الفيديو عالي الجودة يعزّز التفاعل، ويُنشئ ارتباطًا عاطفيًا، وينقل الرسائل بوضوح وفعالية..',
        "sub-category" => "The Track Fit",
        'category' => 'التسويق',
        'before_images' => ['web 1-01-20.webp', 'web 2-21.webp', 'web 3-22.webp', 'web 4-23.webp', 'web 5-24.webp',],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/'
    ],
    [
        'id' => 22,
        'main_image' => 'floor.webp',
        'client' => 'Floor Hub',
        "title" => "Floor Hub",
        "sec-title" => "Media",
        'description' => 'تتخصص Floor Hub في تقديم أرضيات HDF الأوروبية الفاخرة، مع مجموعة واسعة من الألوان العصرية، 100% أصلية، عالية الجودة، ومصممة لتدوم طويلاً.',
        "sub-category" => "Floor Hub",
        'category' => 'التسويق',
        'before_images' => ['web 1-10.webp', 'web 2-11.webp', 'web 3-12.webp', 'web 4-13.webp',],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/'
    ],
    [
        'id' => 23,
        'main_image' => 'Perfumes Unlimited Logo PNG White.webp',
        'client' => 'Perfumes Unlimited',
        "title" => "Perfumes Unlimited",
        "sec-title" => "Media",
        'description' => ' تتخصص Perfume Unlimited في العطور الفاخرة من جميع العلامات التجارية العالمية، مع عطور أصلية 100% ذات جودة عالية.',
        "sub-category" => "Perfumes Unlimited   ",
        'category' => 'التسويق',
        'before_images' => ['web 1-30.webp', 'web 2-31.webp', 'web 3-32.webp', 'web 4-33.webp', 'cover15.webp', 'web 5-34.webp'],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/'
    ],
    [
        'id' => 24,
        'main_image' => 'Wise Logo1.webp',
        'client' => 'Wise',
        "title" => "Wise",
        "sec-title" => "Media",
        'description' => ' تقدّم Wise Egypt منتجات تنظيف عالية الجودة، مصمّمة لتمنح كل منزل انتعاشًا ونظافة وصحّة تدوم طويلاً.',
        "sub-category" => "Wise",
        'category' => 'التسويق',
        'before_images' => ['web 3-40.webp', 'web 4-41.webp', 'web 5-42.webp', 'wise 2-43.webp', 'cover15.webp', 'wise web-01-44.webp'],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/'
    ],
    [
        'id' => 3,
        'main_image' => 'IMG_7741 (1) 1.webp',
        'client' => 'ocean heights',
        "title" => "The website was designed and developed by HSpace",
        "sec-title" => "Media",
        'description' => '',
        'category' => 'انظمة برمجية',
        "sub-category" => "موقع الكتروني",
        'before_images' => ['image 21.webp', 'image 22.webp', 'image 23.webp'],
        'after_images' => ['image 24.webp', 'image 25.webp', 'image 20.webp'],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://oceanheights-eg.com/'
    ],
    [
        'id' => 4,
        'main_image' => 'logo track.webp',
        'client' => 'Track Fit',
        "title" => "The Application was designed and developed by HSpace",
        "sec-title" => "Media",
        'description' => ' وسيلة قوية لسرد القصص تُجسّد جوهر العلامة التجارية من خلال صور جذّابة وسرد مؤثر. فإنتاج الفيديو عالي الجودة يعزّز التفاعل، ويُنشئ ارتباطًا عاطفيًا، وينقل الرسائل بوضوح وفعالية.',
        "sub-category" => "تطبيق",
        'category' => 'انظمة برمجية',
        'before_images' => ['image 15.webp', 'image 16.webp', 'image 17.webp'],
        'after_images' => ['image 18.webp', 'image 19.webp', 'image 16.webp'],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Mobile App Design', 'Smooth and Intuitive User Experience (UX)', 'Cross-Platform Development with Flutter', 'Secure User Authentication', 'Interactive UI Components', 'Real-time Notifications and Updates'],
        'after_list' => ['Advanced Search and Filters', 'Multi-language Support', 'High Performance and Speed', 'Responsive Layout for All Screen Sizes', 'Integration with Device Features (Camera, GPS, etc.)', 'Data Security and Privacy Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => '#'
    ],
    [
        'id' => 5,
        'main_image' => 'colorful-bird-abstract-logo-design_474888-4591 1.webp',
        'client' => 'Farma App',
        "title" => "The Application was designed and developed by HSpace",
        "sec-title" => "Media",
        'description' => '',
        "sub-category" => "تطبيق",
        'category' => 'انظمة برمجية',
        'before_images' => ['image 26.webp', 'image 27.webp', 'image 28.webp'],
        'after_images' => ['image 29.webp', 'image 28.webp', 'image 26.webp'],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Mobile App Design', 'Smooth and Intuitive User Experience (UX)', 'Cross-Platform Development with Flutter', 'Secure User Authentication', 'Interactive UI Components', 'Real-time Notifications and Updates'],
        'after_list' => ['Advanced Search and Filters', 'Multi-language Support', 'High Performance and Speed', 'Responsive Layout for All Screen Sizes', 'Integration with Device Features (Camera, GPS, etc.)', 'Data Security and Privacy Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => '#'
    ],

    [
        'id' => 300,
        'main_image' => 'Asset-4-01.svg',
        'client' => 'El-Sewedy University',
        "title" => "El Sewedy University",
        "sec-title" => "Media",
        'description' => 'تُعَدّ جامعة السويدي للتكنولوجيا (SUT) أوّل جامعة بوليتكنيك في مصر، حيث تقدّم برامج تطبيقية قائمة على التكنولوجيا في مجالات مثل الطاقة والذكاء الاصطناعي. وتهدف إلى تزويد الطلاب بالمهارات اللازمة لمواكبة متطلبات سوق العمل اليوم..
',
        'category' => 'الانتاج الاعلاني',
        "sub-category" => "",
        'before_images' => ['https://www.youtube.com/embed/CX9ImDhRfWQ?si=m1BDbIkEDsnmn7aW',],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://oceanheights-eg.com/'
    ],
    [
        'id' => 301,
        'main_image' => 'nawy.f142e162.svg',
        'client' => 'Nawy',
        "title" => "Nawy",
        "sec-title" => "Media",
        'description' => 'منصة عقارية ذكية تُمكّن المستخدمين من البحث عن العقارات وحجزها دون أي عمولة، كما توفّر حلول تمويل مرنة للمنازل المملوكة مسبقًا عبر خدمتها «Nawy Now».',
        'category' => 'الانتاج الاعلاني',
        "sub-category" => "",
        'before_images' => ['https://www.youtube.com/embed/M6eD5FGzu_U?si=oZaDphphiWbvydAk', 'https://www.youtube.com/embed/_QGdwMTLwEs?si=iNiKheRCQPEQwj6N', 'https://www.youtube.com/embed/M_qr2Kqf7xU?si=O_CtOZcf6X9OdbTV', 'https://www.youtube.com/embed/bIq_xkDsVZk?si=VKTXbSJidJ-R8C0w', 'https://www.youtube.com/embed/RqXSlo0hg5Y?si=fJvGe6Hdj4mUfN1A', 'https://www.youtube.com/embed/uB_9VenOmCY?si=hakDT_HmOnWKKzN7', 'https://www.youtube.com/embed/IW30_zUq0p4?si=eAncm9Eq4PnSL_OE', 'https://www.youtube.com/embed/ViSdAzvvxC8?si=AiW36Mj9ODoo8V5w', 'https://www.youtube.com/embed/hysL-ghDsPk?si=bte-Y_z_rbpyF4ss'],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://oceanheights-eg.com/'
    ],
    [
        'id' => 302,
        'main_image' => 'MMG Logo.webp',
        'client' => 'MMG',
        "title" => "MMG",
        "sec-title" => "Media",
        'description' => 'تُعَدّ MMG مطوّرًا عقاريًا منذ عام 2009، اشتهرت بمشروعات سكنية عصرية في أهم مناطق القاهرة. وتلتزم الشركة بالجودة، وتسليم المشاريع في مواعيدها، مع توفير خيارات دفع مرنة.',
        'category' => 'الانتاج الاعلاني',
        "sub-category" => "",
        'before_images' => ['https://www.youtube.com/embed/zWMqtXPbxhE?si=p1R4s4FNFQ2esFlm', 'https://www.youtube.com/embed/vYvB9gTATxE?si=wT9wcKLd-59y8kxE', 'https://www.youtube.com/embed/C16dDt2NAeY?si=ORGeLrG7Z8gaDYPH', 'https://www.youtube.com/embed/3ReK_o8COYQ?si=Kh-8Udilu2suyecm', 'https://www.youtube.com/embed/eu3nJeTIxbw?si=wbbk5RkQFQJgZiIs', 'https://www.youtube.com/embed/e-pnUorv_xo?si=Thy5pZ58r6AxJytY', 'https://www.youtube.com/embed/kCuJ75620ZA?si=zaSg2ciqQXVczE_b',],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://oceanheights-eg.com/'
    ],
    [
        'id' => 303,
        'main_image' => 'logo7.webp',
        'client' => 'Big Chips',
        "title" => "Big Chips",
        "sec-title" => "Media",
        'description' => 'Big Chips هي علامة تجارية مصرية تقدّم رقائق بطاطس طبيعية 100% بمجموعة متنوّعة من النكهات اللذيذة. وهي جزء من Egypt Foods Group المعروفة بجودة منتجاتها وبتغليفها الجذّاب.',
        'category' => 'الانتاج الاعلاني',
        "sub-category" => "",
        'before_images' => ['image 21.webp', 'image 22.webp', 'image 23.webp'],
        'after_images' => ['image 24.webp', 'image 25.webp', 'image 20.webp'],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://oceanheights-eg.com/'
    ],
    [
        'id' => 100,
        'main_image' => 'Celera Logo1.webp',
        'client' => 'Celera',
        "title" => "Celera",
        "sec-title" => "Media",
        'description' => 'تقدّم Celera منتجات فاخرة تجمع بين جودة استثنائية وأناقة خالدة، وقد صُمّمت خصيصًا لمن يقدّرون التميّز والرقي.',
        "sub-category" => "",
        'category' => 'العلامة التجارية',
        'before_images' => ['cover30.webp', 'cover32.webp', 'cover31.webp', 'cover33.webp',],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/',
    ],
    [
        'id' => 101,
        'main_image' => 'Wise Logo1.webp',
        'client' => 'Wise',
        "title" => "Wise",
        "sec-title" => "Wise",
        'description' => ' تقدّم Wise Egypt منتجات تنظيف عالية الجودة، مصمَّمة لتمنح كل منزل انتعاشًا ونظافة وصحّة تدوم طويلاً.',
        "sub-category" => "",
        'category' => 'العلامة التجارية',
        'before_images' => ['cover20.webp', 'cover21.webp', 'cover22.webp',],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/',
    ],
    [
        'id' => 102,
        'main_image' => 'Marigold  Logo1.webp',
        'client' => 'Marigold',
        "title" => "Marigold",
        "sec-title" => "Marigold",
        'description' => ' تتخصص Mari Gold في المنظّفات المنزلية المتطورة ذات التركيبات المبتكرة، 100% أصلية وعالية الجودة، لحماية أسطح منزلك.',
        "sub-category" => "",
        'category' => 'العلامة التجارية',
        'before_images' => ['cover50.webp', 'cover51.webp', 'cover52  .webp',],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/',
    ],
    [
        'id' => 103,
        'main_image' => 'floor.webp',
        'client' => 'Floor Hub',
        "title" => "FLOOR HUB",
        "sec-title" => "FLOOR HUB",
        'description' => 'تتخصّص Floor Hub في الأرضيات الأوروبية الفاخرة من نوع HDF، مع مجموعة واسعة من الألوان العصرية، أصلية 100%، عالية الجودة، ومصمَّمة لتدوم طويلاً.',
        "sub-category" => "",
        'category' => 'العلامة التجارية',
        'before_images' => ['floor-01.webp', 'floor-07.webp', 'floor-08.webp', 'floor-09.webp', 'floor-10.webp', 'floor-11.webp', 'floor-12.webp', 'floor-13.webp', 'floor-14.webp.webp', 'floor-15.webp', 'floor-16.webp', 'floor-17.webp', 'floor-18.webp', 'floor-19.webp',],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/',
    ],
    [
        'id' => 104,
        'main_image' => 'ishrrq.webp',
        'client' => 'Ishraq',
        "title" => "Ishraq",
        "sec-title" => "Ishraq",
        'description' => 'تتخصّص Ishraq في تقديم خدمات العلاج الطبيعي والتأهيل الفاخرة، مع مجموعة واسعة من العلاجات المتقدمة، باحترافية تامة وجودة عالية، ومصمَّمة لاستعادة قوتك.',
        "sub-category" => "",
        'category' => 'العلامة التجارية',
        'before_images' => ['ishraq-01.webp', 'ishraq-06.webp', 'ishraq-07.webp', 'ishraq-08.webp', 'ishraq-09.webp', 'ishraq-10.webp', 'floor-12.webp', 'ishraq-11.webp', 'ishraq-12.webp', 'ishraq-13.webp', 'ishraq-14.webp', 'ishraq-15.webp', 'ishraq-16.webp', 'ishraq-17.webp',],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/',
    ],

    [
        'id' => 105,
        'main_image' => 'SAK.webp',
        'client' => 'SAK',
        "title" => "SAK",
        "sec-title" => "SAK",
        'description' => 'تُعَدّ SAK Developments شركة رائدة في مجال التطوير العقاري، تتمتّع بأكثر من 35 عامًا من الخبرة المتراكمة، وتقدّم مشروعات سكنية وتجارية ومتعددة الاستخدامات عالية الجودة.',
        "sub-category" => "",
        'category' => 'العلامة التجارية',
        'before_images' => ['sak-06.webp', 'sak-07.webp', 'sak-08.webp', 'sak-09.webp', 'sak-10.webp', 'sak-11.webp', 'sak-12.webp', 'sak-13.webp'],
        'after_images' => [''],
        'stats' => [
            '+50%' => 'Increase in website session duration',
            '+30%' => 'Boost in engagement',
            '+80%' => 'Faster page loads',
            '+10%' => 'Better retention',
        ],
        'before_list' => ['Custom Design', 'Smooth User Experience (UX)', 'Dynamic Admin Dashboard', 'User Authentication System', 'Detailed Product Pages', 'Shopping Cart and Checkout System'],
        'after_list' => ['Advanced Search and Filtering', 'Multi-language Support', 'Performance Optimization', 'Fully Responsive Design', 'Social Media Integration', 'Security and Data Protection'],
        'flags' => [
            'Saudi Flag-01.webp',
            'Flag_of_Egypt.svg',
        ],
        'url' => 'https://nehalsamy.com/',
    ],



];
